### ISSUE TITLE
Automation to build mservctl binaries

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/mserv#11]
mservctl must be built once a release version is tagged. The resulting binaries must be attached to the GH release.

In order to build mservctl the following command needs to be executed in `mservctl` directory:
```
go build -mod=vendor
```

Binaries need to be built for Linux x86_64 and macOS x86_64. Possibly Windows too, but needs to be tested.

**Comment by alephnull** [comment]
I am not very familiar with Windows build procedures. I will deliver linux and macos first while I figure out Windows. Since it is a single binary, we should be able to package it for homebrew which should make it trivial to install.

For Windows, chocolatey might be an option.

**Comment by excieve** [comment]
@alephnull Don't worry about Windows binaries for now, we never tried this app on it anyway, so even if distributed should be clearly marked as "experimental".

**Comment by alephnull** [comment]
PR: https://github.com/TykTechnologies/mserv/issues/11
